Fix warnings -Wunused-variable in release
This fixes the following warning in release

src/lib/support/Pool.cpp:69:10: error: unused variable 'value' [-Werror,-Wunused-variable]
    auto value = mUsage[word].fetch_and(~(kBit1 << offset));

Switch to nlassert since this macro doesn't cause unused variable
warnings when assertions are disabled.